export enum PropertyType {
	HOTEL = 'HOTEL',
	RESORT = 'RESORT',
	HOSTEL = 'HOSTEL'
}

export enum PropertyStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	DAEJON = 'DAEJON',
	GWANGJU = 'GWANGJU',
    ULSAN = 'ULSAN',
    SEJONG = 'SEJONG',
    GYEONGGI = 'GYEONGGI',
    GANGWON = 'GANGWON',
    CHUNGCHEONGBUK = 'CHUNGCHEONGBUK',
    CHUNGCHEONGNAM = 'CHUNGCHEONGNAM',
    JEOLLABUK = 'JEOLLABUK',
    JEOLLANAM = 'JEOLLANAM',
    GYEONGSANGBUK = 'GYEONGSANGBUK',
    GYEONGSANGNAM = 'GYEONGSANGNAM',
	JEJU = 'JEJU',
}

export enum PropertyAmenity {
	WIFI = 'WIFI',
	POOL = 'POOL',
	BREAKFAST = 'BREAKFAST',
	PARKING = 'PARKING',
	AC = 'AC',
	GYM = 'GYM',
}
